mail_server = {
    "org1": {
        "SMTP_HOST": "",
        "SMTP_PORT": 25,
        "SEND_FROM": "test@example.com",
        "SEND_NAME": None,
        "REPLY_TO": None,
        "REPLY_NAME": None,
        "ENVELOPE_FROM": None,
        "SSL_ENABLE": 0,
        "START_TLS_ENABLE": 0,
        "AUTHENTICATION_ENABLE": 0,
        "AUTHENTICATION_USER": None,
        "AUTHENTICATION_PASSWORD": None,
    },
    "org2": {
        "SMTP_HOST": "",
        "SMTP_PORT": 25,
        "SEND_FROM": "test@example.com",
        "SEND_NAME": None,
        "REPLY_TO": None,
        "REPLY_NAME": None,
        "ENVELOPE_FROM": None,
        "SSL_ENABLE": 0,
        "START_TLS_ENABLE": 0,
        "AUTHENTICATION_ENABLE": 0,
        "AUTHENTICATION_USER": None,
        "AUTHENTICATION_PASSWORD": None,
    },
    "org3": {
        "SMTP_HOST": "",
        "SMTP_PORT": 25,
        "SEND_FROM": "test@example.com",
        "SEND_NAME": None,
        "REPLY_TO": None,
        "REPLY_NAME": None,
        "ENVELOPE_FROM": None,
        "SSL_ENABLE": 0,
        "START_TLS_ENABLE": 0,
        "AUTHENTICATION_ENABLE": 0,
        "AUTHENTICATION_USER": None,
        "AUTHENTICATION_PASSWORD": None,
    },
    "org4": {
        "SMTP_HOST": "",
        "SMTP_PORT": 25,
        "SEND_FROM": "test@example.com",
        "SEND_NAME": None,
        "REPLY_TO": None,
        "REPLY_NAME": None,
        "ENVELOPE_FROM": None,
        "SSL_ENABLE": 1,
        "START_TLS_ENABLE": 0,
        "AUTHENTICATION_ENABLE": 0,
        "AUTHENTICATION_USER": None,
        "AUTHENTICATION_PASSWORD": None,
    },
    "org5": {
        "SMTP_HOST": "",
        "SMTP_PORT": 25,
        "SEND_FROM": "test@example.com",
        "SEND_NAME": None,
        "REPLY_TO": None,
        "REPLY_NAME": None,
        "ENVELOPE_FROM": None,
        "SSL_ENABLE": 0,
        "START_TLS_ENABLE": 0,
        "AUTHENTICATION_ENABLE": 0,
        "AUTHENTICATION_USER": None,
        "AUTHENTICATION_PASSWORD": None,
    },
}

mail_to = [
    "test@example.com",
]