[tool.poetry]
name = "platform-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = ">=0.0.0"
pyyaml = ">=0.0.0"
flask = ">=0.0.0"
pytz = ">=0.0.0"
markdown = ">=0.0.0"
pyjwt = ">=0.0.0"
python-dotenv = ">=0.0.0"
flask-log-request-id = ">=0.0.0"
connexion = {version = ">=0.0.0", extras = ["swagger-ui"]}
six = ">=0.0.0"
pymysql = ">=0.0.0"
pycryptodome = ">=0.0.0"
email-validator = ">=0.0.0"
cryptography = ">=0.0.0"
python-ulid = ">=0.0.0"


[tool.poetry.group.first_install.dependencies]
certifi = ">=0.0.0"


[tool.poetry.group.develop_build.dependencies]
debugpy = ">=0.0.0"
flake8 = ">=0.0.0"
autopep8 = ">=0.0.0"
pytest = ">=0.0.0"
pytest-env = ">=0.0.0"
pytest-cov = ">=0.0.0"
pytest-docker = ">=0.0.0"
pytest-mock = ">=0.0.0"
requests-mock = ">=0.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
