CREATE USER `PF_ORG_4AE9R2CERSRAF0MVILML`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$:Wnm\"3E:S*Hyd*;?sCQHBstUQrilh.cznJlcW55FskZxk2GNIaDi/KU8YKA' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_4AE9R2CERSRAF0MVILML`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_4ae9r2cersraf0mvilml`.* TO `PF_ORG_4AE9R2CERSRAF0MVILML`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_AND420H4QHCN6Y0MFP3D`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$Z#\rGo{\'x,~\"-Fg^YxgKct6xHbhElxNZk.CqMSGJb0Gt7pZa4KZnHNjO8h5' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_AND420H4QHCN6Y0MFP3D`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_and420h4qhcn6y0mfp3d`.* TO `PF_ORG_AND420H4QHCN6Y0MFP3D`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_FBS5K921EBBN3IFOJP6P`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$ /59j|\nP[rkK	WvV_;o.dHQArwq7nemLO821Y7kHIkqBlXWL2.dG7NRM4subB' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_FBS5K921EBBN3IFOJP6P`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_fbs5k921ebbn3ifojp6p`.* TO `PF_ORG_FBS5K921EBBN3IFOJP6P`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_K78XP1TIPKAVFIN3KND8`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$\"chA]#	Jdr,9}3v6.}\rr8ANKfO6zEOA1LGtcwTsHNArMVyP.qc/MRhtHjdkO7q6' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_K78XP1TIPKAVFIN3KND8`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_k78xp1tipkavfin3knd8`.* TO `PF_ORG_K78XP1TIPKAVFIN3KND8`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_WSGD5NKTQURIJ2RZGX13`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$q \Z)_{eE,t&;\ZD2+XPiSQQZu9eSgVNky9VZvJznBjBv3yN9NruHT2lcSRkB/' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_WSGD5NKTQURIJ2RZGX13`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_wsgd5nktqurij2rzgx13`.* TO `PF_ORG_WSGD5NKTQURIJ2RZGX13`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_0SPWXQ2GTVVRJS96B8F5`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$|J;\\1Fw{)U%^foYO@luCRALC5POMhPq/ayQFQSolUH9fQIRYzhhfpnQH99WD' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_0SPWXQ2GTVVRJS96B8F5`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_0spwxq2gtvvrjs96b8f5`.* TO `PF_WS_0SPWXQ2GTVVRJS96B8F5`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_0V3X6GSI8D74B6XZWH99`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$3&ZAa+4\ZW~Q.1s/.nI0aB7csLps9lsRljxhqwAyjPAPv9O0wBiTWKx0p3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_0V3X6GSI8D74B6XZWH99`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_0v3x6gsi8d74b6xzwh99`.* TO `PF_WS_0V3X6GSI8D74B6XZWH99`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_4IOGBW61IVUZH0S6PF07`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$,QA[{U&LJHW/jdfHlT.cbsl/iGZbGdeKcFczyHvxL/5.HB8GTnB' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_4IOGBW61IVUZH0S6PF07`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_4iogbw61ivuzh0s6pf07`.* TO `PF_WS_4IOGBW61IVUZH0S6PF07`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_4PK8QJADEX04ZUMG2Q1P`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$R_{AM 8/[JyD8eTRByqZTvQ6YRB6QiKeA7z6CEjLj.vhPoszNaV3nigW22' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_4PK8QJADEX04ZUMG2Q1P`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_4pk8qjadex04zumg2q1p`.* TO `PF_WS_4PK8QJADEX04ZUMG2Q1P`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_5UTX18J9HUT0VWJFA6EI`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$.0x\n(,`0%#\"ycjDinl9rTcmWzUV8YvlGBZFlanOcuq.d47LEmnvaPk9' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_5UTX18J9HUT0VWJFA6EI`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_5utx18j9hut0vwjfa6ei`.* TO `PF_WS_5UTX18J9HUT0VWJFA6EI`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_7UGWWADYAHXPCI440LUG`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$<jZb:;LT%qO9]qisJNnH9vq5i9DYDOCZmYWL4kQJMhPKHGpjquQ6cOnAB4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_7UGWWADYAHXPCI440LUG`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_7ugwwadyahxpci440lug`.* TO `PF_WS_7UGWWADYAHXPCI440LUG`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_94N45AR7K9950YQ4K25S`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$Id^P{Tr/CK1\" Y?!Yz3QLabESntODCgKqkF2zs88NOgVUe3gRI.zvCtisjJQ2' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_94N45AR7K9950YQ4K25S`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_94n45ar7k9950yq4k25s`.* TO `PF_WS_94N45AR7K9950YQ4K25S`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_B6IQMVHETFBS4B3V41CX`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$}DU<#\\mw.\Z:tvU|LGi/CYrjICAdYHmLXOJQPjBrO.bsXW9T4YcJhw.Qecr4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_B6IQMVHETFBS4B3V41CX`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_b6iqmvhetfbs4b3v41cx`.* TO `PF_WS_B6IQMVHETFBS4B3V41CX`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_FIZ0I880E8KI561TY2LB`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$-f&&rY-tAI.Moq%~{XBMT9XpYabwBR8MgpNu9Ecopa.64X0N2zkW6cMElnCn/' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_FIZ0I880E8KI561TY2LB`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_fiz0i880e8ki561ty2lb`.* TO `PF_WS_FIZ0I880E8KI561TY2LB`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_M8IFJAJENM44L2FQWS73`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$O?=XF}[@oAU/8BY\\Z94sO2Yvw6f6/PkB1IvUUO/EJFZJnz9UfpPYV4nW5y.' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_M8IFJAJENM44L2FQWS73`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_m8ifjajenm44l2fqws73`.* TO `PF_WS_M8IFJAJENM44L2FQWS73`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_RFJF11WBWAT411V1B1ZW`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$j6SI},Ku%`ghx-q+L7vWVL1YkwXb82CJk8K5qhVUBIUrUlHSLiQpBHiOlYiB' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_RFJF11WBWAT411V1B1ZW`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_rfjf11wbwat411v1b1zw`.* TO `PF_WS_RFJF11WBWAT411V1B1ZW`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_U1MUZ40O87ZZ8QB4F8Z8`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$?NZP\r&(`y{C&4hSHvL9oi/kBKMRKit/wPTgdW6Mjlfv31wlnAI/ucU95YB' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_U1MUZ40O87ZZ8QB4F8Z8`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_u1muz40o87zz8qb4f8z8`.* TO `PF_WS_U1MUZ40O87ZZ8QB4F8Z8`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_U2UT99BI7HWQPRZV4Q20`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$#^0WP?B5p_deq\rV0u2VKsapln1oMTcbnXU66C27bhtZsL9mxlU2MmAOysGU4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_U2UT99BI7HWQPRZV4Q20`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_u2ut99bi7hwqprzv4q20`.* TO `PF_WS_U2UT99BI7HWQPRZV4Q20`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_VOLCFQBOSN89U15RRLUY`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$%C\'9u9O-c)4MvHqLj8s3GaQctFSZMFm3jDfPR.R8aXI.6RGFyygbSN.W4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_VOLCFQBOSN89U15RRLUY`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_volcfqbosn89u15rrluy`.* TO `PF_WS_VOLCFQBOSN89U15RRLUY`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_WY6DV85WD899WO4KAHPO`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$1`JkezYdNPv?+yV?y	omcKdOw70fG3/c9PmGxheVK8RqSkJHT.ri.t6qFyb..' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_WY6DV85WD899WO4KAHPO`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_wy6dv85wd899wo4kahpo`.* TO `PF_WS_WY6DV85WD899WO4KAHPO`@`%` WITH GRANT OPTION;
CREATE USER `app_user`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$rQxX+QbT\"1wMV[v2xrJc9aIxkeSrfZbt9AUu/y1iIPcbivUEayt1lbRK2' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `app_user`@`%`;
GRANT ALL PRIVILEGES ON `platform`.* TO `app_user`@`%`;
CREATE USER `keycloak`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$QCBKB3 \Z-mp3SJsoSRsrxcx9EyeAejpXsddps8oZuJF6xe.EWneuLKc/' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `keycloak`@`%`;
GRANT ALL PRIVILEGES ON `keycloak`.* TO `keycloak`@`%`;
