CREATE USER `PF_ORG_G3676GHVZ8QMO4WM0ET4`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$\"4YcxdVH.s?4sW~CoMAd7frDbfrPdgO5PCRzxSJACRbnPF.dsTS7Svenw4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_G3676GHVZ8QMO4WM0ET4`@`%`;
GRANT ALL PRIVILEGES ON `PF_ORG_G3676GHVZ8QMO4WM0ET4`.* TO `PF_ORG_G3676GHVZ8QMO4WM0ET4`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_GO317MI11YMGSUAWE06E`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$eX,L{-`dv/o<\\f`\\kwC/7mEKbYewP2.Puz6XXQg1AK33r5MbIoBWnRdy4P/' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_GO317MI11YMGSUAWE06E`@`%`;
GRANT ALL PRIVILEGES ON `PF_ORG_GO317MI11YMGSUAWE06E`.* TO `PF_ORG_GO317MI11YMGSUAWE06E`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_ILFVRK8TCET6PAVC6HTQ`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$gP6!^Y#;xn@6k/Smq{tVTJTvRc/1ttP7UAy5E7xEKQnKTlpvn61x43KnVBlL.' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_ILFVRK8TCET6PAVC6HTQ`@`%`;
GRANT ALL PRIVILEGES ON `PF_ORG_ILFVRK8TCET6PAVC6HTQ`.* TO `PF_ORG_ILFVRK8TCET6PAVC6HTQ`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_R5R95XWTSOCAU0A9Q2N8`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$.{\\\'AQISZUwuA_\rjp1McloITH4BDRDQPdKq00p1rYq5rymHrteN448/Gp1' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_R5R95XWTSOCAU0A9Q2N8`@`%`;
GRANT ALL PRIVILEGES ON `PF_ORG_R5R95XWTSOCAU0A9Q2N8`.* TO `PF_ORG_R5R95XWTSOCAU0A9Q2N8`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_WC3G967VY0SAFBNI91QQ`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$S0=-F*u=_Dn_2iRq25m5PVFUQJCB0iWfYWhAA5WWwfbsOgTL5MvUvNA5' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_WC3G967VY0SAFBNI91QQ`@`%`;
GRANT ALL PRIVILEGES ON `PF_ORG_WC3G967VY0SAFBNI91QQ`.* TO `PF_ORG_WC3G967VY0SAFBNI91QQ`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_05ZO7AX96PDJXSBXJQRD`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$O6[8#t)|mj89OwLx.dXNGBKBARO9fGRveLu2mbhOqMN8fQmTImVUsaPD3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_05ZO7AX96PDJXSBXJQRD`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_05ZO7AX96PDJXSBXJQRD`.* TO `PF_WS_05ZO7AX96PDJXSBXJQRD`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_06KZCQI0ASDEHHUJSESN`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$W@>^R<[X~k@=={5No/iL6KWWrcvj2vmmsx7lZH101jkxmwbdchtj/YGM4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_06KZCQI0ASDEHHUJSESN`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_06KZCQI0ASDEHHUJSESN`.* TO `PF_WS_06KZCQI0ASDEHHUJSESN`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_61TI3JSFBJAH5DEB5UWR`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$)w\\6she*r}\\Xd({RwEcMNUQVHyBl83YH8b2hTWsENj0icLYFRZvh5cBQuC' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_61TI3JSFBJAH5DEB5UWR`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_61TI3JSFBJAH5DEB5UWR`.* TO `PF_WS_61TI3JSFBJAH5DEB5UWR`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_771NHLECQ1NADGYE4MSX`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$V0zGUUE~~Cz!\'#@(MUhU79SJBcx8lm5bKBLNcnazKLUlWI60Eh5FvkQ4.P3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_771NHLECQ1NADGYE4MSX`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_771NHLECQ1NADGYE4MSX`.* TO `PF_WS_771NHLECQ1NADGYE4MSX`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_78YFC9PPGDH47EMUJCUI`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$rq\\!\'l:k<(XD89t9RDp9ayUJ92ItFHo7YRGaWoKH0UK6js5PXvXF.7' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_78YFC9PPGDH47EMUJCUI`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_78YFC9PPGDH47EMUJCUI`.* TO `PF_WS_78YFC9PPGDH47EMUJCUI`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_C4NIATSX45YYBGY5JDQZ`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$:z\\ey\rSWO0zCpTZ{v3sWgB/g.F2PKRxejgGrr.BK0BSpT9pYVy1NQQPfqK0' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_C4NIATSX45YYBGY5JDQZ`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_C4NIATSX45YYBGY5JDQZ`.* TO `PF_WS_C4NIATSX45YYBGY5JDQZ`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_DE2QS33N1S0Y1HOO8MPR`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$0s}Fi9X<Nrt{H@OCzPJianZAMpZ5nsse0aasorBFiJoX/f804UaoCoz5TB3/' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_DE2QS33N1S0Y1HOO8MPR`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_DE2QS33N1S0Y1HOO8MPR`.* TO `PF_WS_DE2QS33N1S0Y1HOO8MPR`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_ERV7QPKK2SGJBAW3AP4I`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$F%Kcr/MR>VVDaE#{7RcVmRQjt5lRBJJ3PIydgCd8KhayEh2Qfekj91JCa27' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_ERV7QPKK2SGJBAW3AP4I`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_ERV7QPKK2SGJBAW3AP4I`.* TO `PF_WS_ERV7QPKK2SGJBAW3AP4I`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_HHYBNMJB55RLO0BGZ0IP`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$%F0fe<.jA(\ZKo=DhmuocoGWno.k9BT77DMecffePj/R9I8fkUnfMAWDD3C' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_HHYBNMJB55RLO0BGZ0IP`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_HHYBNMJB55RLO0BGZ0IP`.* TO `PF_WS_HHYBNMJB55RLO0BGZ0IP`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_HU13UUYX4LUR2UGRVM8O`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$qu%T#k@>H \"{8>\ZVb7HFeX.1VaaBHHH3c9K1IiZ3OecbpuGsrEg6uTl.m2Q3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_HU13UUYX4LUR2UGRVM8O`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_HU13UUYX4LUR2UGRVM8O`.* TO `PF_WS_HU13UUYX4LUR2UGRVM8O`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_IAJR8E603MKXP3C54WV8`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$%`e|Z<1\"d9+p|Jwszjv0.Q5JgWrSSAA9vboXzic7ipKe0m9ZWvHCJD/k9' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_IAJR8E603MKXP3C54WV8`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_IAJR8E603MKXP3C54WV8`.* TO `PF_WS_IAJR8E603MKXP3C54WV8`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_QGJJ8AIR5EIT23YFNSV2`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$p,t?ZyhTz{W=2d\\k9iKX15e583QaJZcHVQkk6.BKP0Iv2K7/ahoAfUuL92' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_QGJJ8AIR5EIT23YFNSV2`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_QGJJ8AIR5EIT23YFNSV2`.* TO `PF_WS_QGJJ8AIR5EIT23YFNSV2`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_QWTWM2E21EJF4EOKA14L`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$vB5#U[\\jqXD?SBZ83YfPeQtsNupw83fk5TLEI6Tn8jEldxp3WH9Sut3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_QWTWM2E21EJF4EOKA14L`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_QWTWM2E21EJF4EOKA14L`.* TO `PF_WS_QWTWM2E21EJF4EOKA14L`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_VCUJL5K7R9JT8ERVJU2H`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$02!\\=GprXjK@VomTpoUj6PkB7Yg4l/yZccO57158vFptBBPLXG9smT0' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_VCUJL5K7R9JT8ERVJU2H`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_VCUJL5K7R9JT8ERVJU2H`.* TO `PF_WS_VCUJL5K7R9JT8ERVJU2H`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_WSHZ1MN2L7DUGRIZB10V`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$QJ}7W%vLuxfOZ\nijvoCuXamGSCq3up75du9D/PVfva8bj9QODDPB32.Z5' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_WSHZ1MN2L7DUGRIZB10V`@`%`;
GRANT ALL PRIVILEGES ON `PF_WS_WSHZ1MN2L7DUGRIZB10V`.* TO `PF_WS_WSHZ1MN2L7DUGRIZB10V`@`%` WITH GRANT OPTION;
CREATE USER `app_user`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$YC)+j,	p%kve_39]kasJgpyCgaxx6BJLbSyhcPSElT8ZMlCWfx6nM9qjOP3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `app_user`@`%`;
GRANT ALL PRIVILEGES ON `platform`.* TO `app_user`@`%`;
CREATE USER `keycloak`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$UrfN(Vk/!w@MVfFRyCdafeM5raX21rcY2FJIuUmCQce3RBt73ZMUSw4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `keycloak`@`%`;
GRANT ALL PRIVILEGES ON `keycloak`.* TO `keycloak`@`%`;
