CREATE USER `PF_ORG_2XGBSHJR1WWAN3MFATTD`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$2{ x 953Id!>~pp3nrbpnPYeBwkjY7QUwNaUDb.fE//tpCRyVkv6jlmD' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_2XGBSHJR1WWAN3MFATTD`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_2xgbshjr1wwan3mfattd`.* TO `PF_ORG_2XGBSHJR1WWAN3MFATTD`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_34JZDH9VRGFR8MNP82QP`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$>Rh75Rrupy~%km07g5TCZenSMyoiU5fZdkKbWa/0/kbkyy4XFWzp8jA0' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_34JZDH9VRGFR8MNP82QP`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_34jzdh9vrgfr8mnp82qp`.* TO `PF_ORG_34JZDH9VRGFR8MNP82QP`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_NYD2293U02I3NNADA1DC`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$sgvfK,\nYMs\"Z2jE&V/hW/UIw5yeAG6GzXGi6P4g5JzERA3z5xTQnKKa4wY1' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_NYD2293U02I3NNADA1DC`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_nyd2293u02i3nnada1dc`.* TO `PF_ORG_NYD2293U02I3NNADA1DC`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_PHHDQF9F47JGCZNKQ2IV`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$wP\ZgZo@%]1ZzcEkjMxL1nNUlczoW/hno3OFL.nCdix4ay5Xh.TGFnXhBhWC' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_PHHDQF9F47JGCZNKQ2IV`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_phhdqf9f47jgcznkq2iv`.* TO `PF_ORG_PHHDQF9F47JGCZNKQ2IV`@`%` WITH GRANT OPTION;
CREATE USER `PF_ORG_XIH7EEJPFA5Q51WX08RP`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$P@jNv\")Zv@6Qd>jYIqiRZ36uN36IuQaTNL3nv79bkFIz6uwlaXyjMDW6D' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_ORG_XIH7EEJPFA5Q51WX08RP`@`%`;
GRANT ALL PRIVILEGES ON `pf_org_xih7eejpfa5q51wx08rp`.* TO `PF_ORG_XIH7EEJPFA5Q51WX08RP`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_41GIBKB39G9VGTJJR2U7`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$(HGiCB1D~\\FHBWYKyN1N5.uo2VRbJ5D1WlaoBmxH89gkZAQXyH6e3MxN2Rl0' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_41GIBKB39G9VGTJJR2U7`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_41gibkb39g9vgtjjr2u7`.* TO `PF_WS_41GIBKB39G9VGTJJR2U7`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_5C28S5JEXDPWQN35D0B7`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$\n6I\r@0gz]}\\^5r%dUTJHlo7H2Bk0qPTVcSF9FhScqkOU2l/mh6POJUF/lmA' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_5C28S5JEXDPWQN35D0B7`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_5c28s5jexdpwqn35d0b7`.* TO `PF_WS_5C28S5JEXDPWQN35D0B7`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_5TCA7U1DOUZQSWLK7SOU`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$h#`G	\"^`\rFPW#P8nTukXcJ3MK.9Kj/TtxXMa3zNnf9gXD0tkmiJ4DTE4' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_5TCA7U1DOUZQSWLK7SOU`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_5tca7u1douzqswlk7sou`.* TO `PF_WS_5TCA7U1DOUZQSWLK7SOU`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_6RAB8MOSWAMFEXE81EBE`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$@(vN1~D}XdQ6/ZLHHHB93DFLlYj3slQ/1I0qB3VkjiEbPBXrjfJbfbaidxC' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_6RAB8MOSWAMFEXE81EBE`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_6rab8moswamfexe81ebe`.* TO `PF_WS_6RAB8MOSWAMFEXE81EBE`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_9DZ8987EPPE822DH439B`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$2mnh{0FjN\\.NoIgw/T73KJ9wxBdGD8B/3WYYkl.7nFyq8u31jx9ftak/R.uA' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_9DZ8987EPPE822DH439B`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_9dz8987eppe822dh439b`.* TO `PF_WS_9DZ8987EPPE822DH439B`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_EBGXS1NARY70ZRP1NJOD`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$ns~XXp+2rbuW|b2JqPykmLIUrkMXfZfd4l4cqczHFh8xXS7oMkWY5NOcV2' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_EBGXS1NARY70ZRP1NJOD`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_ebgxs1nary70zrp1njod`.* TO `PF_WS_EBGXS1NARY70ZRP1NJOD`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_FLEG6P0K0YDWNMUGD399`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$Q\Zb0rT\\LV`gj2]rldaPhv2kLUAI7aq6A.oc19eeQWmQ2ODOW3hFA5TzG1' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_FLEG6P0K0YDWNMUGD399`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_fleg6p0k0ydwnmugd399`.* TO `PF_WS_FLEG6P0K0YDWNMUGD399`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_G17HOJJLRN79S1PRM2BS`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$\r^_\'o)k(ekl?W^/ZkmPXPnGVJhesQiynrKnRR7CSSmNPK/BuI.8QA0HxwC' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_G17HOJJLRN79S1PRM2BS`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_g17hojjlrn79s1prm2bs`.* TO `PF_WS_G17HOJJLRN79S1PRM2BS`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_INMQD0KWDAMO81D1SKGN`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$Xs#a\\l9_Igp|F!`	#FUTKcRep31v..nFvbzJQZE.T.lUXVjmKg4gb2uba1eU7' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_INMQD0KWDAMO81D1SKGN`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_inmqd0kwdamo81d1skgn`.* TO `PF_WS_INMQD0KWDAMO81D1SKGN`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_IXPRC3CRF8W64LJZAGYM`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$.+J5Pju,d9/L9	mMDtt21UJyaXJS9g3mwPNeeY3glGFHZ6Mi87YSiFTL86' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_IXPRC3CRF8W64LJZAGYM`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_ixprc3crf8w64ljzagym`.* TO `PF_WS_IXPRC3CRF8W64LJZAGYM`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_J4VUU8EL0ZTDW2RC43IP`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$C+DF+g)~eTkxmObBfkpycuIhpjcU3imVLQx9SH73ZQLxTBoW3kBlv.0' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_J4VUU8EL0ZTDW2RC43IP`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_j4vuu8el0ztdw2rc43ip`.* TO `PF_WS_J4VUU8EL0ZTDW2RC43IP`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_MTHTY40ZFQLNHPJB56YL`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$^S|[_7S!eJer{+\"UTkz7InWVUYonCM3Lh3pnxxrk20f0XeLy8hXPcXRDrL3' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_MTHTY40ZFQLNHPJB56YL`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_mthty40zfqlnhpjb56yl`.* TO `PF_WS_MTHTY40ZFQLNHPJB56YL`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_T9A130MA1M6BJBBPNNAL`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$~fE8#[up6Sx:%O8B\\\"eveyCyo/j9JpLDSOwLlK4xvBzoSrUVuLl2EDTs0CCaC' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_T9A130MA1M6BJBBPNNAL`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_t9a130ma1m6bjbbpnnal`.* TO `PF_WS_T9A130MA1M6BJBBPNNAL`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_TZZZVQ2H9PC8I9E3ONBL`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$p1r(d[&&]%n`;3H5yFlpokUKPZiPnhHx9/99bkfy3FagHMwOri1HuDPXD' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_TZZZVQ2H9PC8I9E3ONBL`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_tzzzvq2h9pc8i9e3onbl`.* TO `PF_WS_TZZZVQ2H9PC8I9E3ONBL`@`%` WITH GRANT OPTION;
CREATE USER `PF_WS_UTVEVQ3DCAUSF27Q2NJP`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$m3<YCCfr>.|_T}BC53uAW9KJ96sd50oD4ZWDbkrRby/Hfk29JYbShvLRF1' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `PF_WS_UTVEVQ3DCAUSF27Q2NJP`@`%`;
GRANT ALL PRIVILEGES ON `pf_ws_utvevq3dcausf27q2njp`.* TO `PF_WS_UTVEVQ3DCAUSF27Q2NJP`@`%` WITH GRANT OPTION;
CREATE USER `app_user`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$7oO&\'^P_bI^z(Q5tx~L0/hW99PB8vZQmmHRRa5x.0YoKjPqKsyrg3lr6nUUW5' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `app_user`@`%`;
GRANT ALL PRIVILEGES ON `platform`.* TO `app_user`@`%`;
CREATE USER `keycloak`@`%` IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$}\\Y1Ftx9/\Zx\\0isnqVbpE3bI3yNn.LSp8QrSack.aHuUFuxOIvGWygG.C' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `keycloak`@`%`;
GRANT ALL PRIVILEGES ON `keycloak`.* TO `keycloak`@`%`;
