#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-platform-common
  namespace: exastro-platform
data:
  TZ: "Asia/Tokyo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ita
  namespace: exastro-platform
data:
  ITA_WEB_PROTOCOL: "http"
  ITA_WEB_HOST: "ita-web-server.exastro-it-automation.svc"
  ITA_WEB_PORT: "8000"
  ITA_API_PROTOCOL: "http"
  ITA_API_HOST: "ita-api-organization.exastro-it-automation.svc"
  ITA_API_PORT: "8080"
  ITA_API_ADMIN_PROTOCOL: "http"
  ITA_API_ADMIN_HOST: "ita-api-admin.exastro-it-automation.svc"
  ITA_API_ADMIN_PORT: "8080"
