#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

openapi: 3.0.3

info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.9.0

servers:
  - url: "https://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "http://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "{protocol}://{host}:{port}"
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30080'

tags:
- name: TokenService
  description: tokenに関する操作
- name: OrganizationService
  description: オーガナイゼーションに関する操作
- name: PlanService
  description: プランに関する操作
- name: UsageService
  description: リソース使用量に関する操作
- name: WorkspaceService
  description: ワークスペースに関する操作
- name: UsersService
  description: ユーザーに関する操作
- name: RoleService
  description: ロールに関する操作
- name: RoleMappingsService
  description: ロール・マッピングに関する操作
- name: JobsService
  description: ジョブに関する操作
- name: MaintenanceModeService
  description: メンテナンスモードに関する操作
- name: NotificationService
  description: 通知機能に関する操作
- name: AuditLogService
  description: 監査ログに関する操作
- name: CommonService
  description: システム設定に関する操作

paths:
  "/auth/realms/{organization_id}/protocol/openid-connect/token":
      $ref: './paths/protocol.openid-connect.token.yaml'
  "/api/{organization_id}/platform/users/_current/refresh_tokens":
      $ref: './paths/user.current.refresh_tokens.yaml'

  "/api/{organization_id}/platform/setting":
      $ref: './paths/organization.setting.yaml'

  "/api/{organization_id}/platform/limits":
      $ref: './paths/plans.organizations.limits.yaml'

  "/api/{organization_id}/platform/usages":
      $ref: './paths/usages.organizations.yaml'

  "/api/{organization_id}/platform/maintenance-mode-setting":
      $ref: './paths/maintenance_mode_setting_organizations.yaml'

  "/api/{organization_id}/platform/workspaces":
      $ref: './paths/workspaces.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}":
      $ref: './paths/workspaces.workspace_id.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}/members":
      $ref: './paths/workspaces.workspace_id.members.yaml'

  "/api/{organization_id}/platform/workspaces/{workspace_id}/notifications":
      $ref: './paths/workspaces.workspace_id.notifications.yaml'

  "/api/{organization_id}/platform/users":
      $ref: './paths/users.yaml'
  "/api/{organization_id}/platform/users/{user_id}":
      $ref: './paths/users.user_id.yaml'

  "/api/{organization_id}/platform/roles":
      $ref: './paths/roles.yaml'
  "/api/{organization_id}/platform/roles/{role_name}":
      $ref: './paths/roles.role_name.yaml'

  "/api/{organization_id}/platform/roles/{role_name}/users":
      $ref: './paths/roles.role_name.users.yaml'

  "/api/{organization_id}/platform/jobs/users/bulk/format":
      $ref: './paths/jobs.users.bulk.format.yaml'

  "/api/{organization_id}/platform/jobs/users/bulk/import":
      $ref: './paths/jobs.users.bulk.import.yaml'

  "/api/{organization_id}/platform/jobs/users/bulk/delete":
      $ref: './paths/jobs.users.bulk.delete.yaml'

  "/api/{organization_id}/platform/jobs/users/bulk/status":
      $ref: './paths/jobs.users.bulk.status.yaml'

  # "/api/{organization_id}/platform/jobs/users/bulk/status/{job_id}":
  #     $ref: './paths/jobs.users.bulk-status.job_id.yaml'

  "/api/{organization_id}/platform/jobs/users/bulk/status/{job_id}/download":
      $ref: './paths/jobs.users.bulk.status.job_id.download.yaml'

  "/api/{organization_id}/platform/jobs/users/export":
      $ref: './paths/jobs.users.export.yaml'

  "/api/{organization_id}/platform/jobs/users/export/status":
      $ref: './paths/jobs.users.export.status.yaml'

  # "/api/{organization_id}/platform/jobs/users/export/status/{job_id}":
  #     $ref: './paths/jobs.users.export-status.job_id.yaml'

  "/api/{organization_id}/platform/jobs/users/export/status/{job_id}/download":
      $ref: './paths/jobs.users.export.status.job_id.download.yaml'

  "/api/{organization_id}/platform/auditlog/download":
      $ref: './paths/auditlog.download.yaml'
  "/api/{organization_id}/platform/auditlog/download/{download_id}":
      $ref: './paths/auditlog.download.download_id.yaml'

  "/api/{organization_id}/platform/settings/common/{config_key}":
      $ref: './paths/common.settings.organizations.common.config.yaml'

components:
  schemas:
    $ref: './schemas/_schemas.yaml'

  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

security:
- BearerAuth: []
- BasicAuth: []