#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories#excluding-directories-from-secret-scanning-alerts-for-users
#
paths-ignore:
  - "platform_root/platform_api/tests/db/exports/**"
  - "platform_root/platform_api/pytest.ini.sample"
  - "platform_root/platform_job/tests/db/exports/**"
  - "platform_root/platform_job/pytest.ini.sample"
