version: 2
secret:
  # 以下に追加した場合は、".github/secret_scanning.yml"にも記載すること
  ignored_paths:
    - 'platform_root/platform_api/pytest.ini.sample'
    - 'platform_root/platform_api/tests/db/exports/**'
    - 'platform_root/platform_job/pytest.ini.sample'
    - 'platform_root/platform_job/tests/db/exports/**'
