CREATE USER app_user IDENTIFIED BY 'password';
CREATE DATABASE platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON platform.* TO app_user;

USE platform;

CREATE TABLE IF NOT EXISTS T_ORGANIZATION
(
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  ORGANIZATION_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_DB
(
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  DB_HOST VARCHAR(255),
  DB_PORT INT,
  DB_DATABASE VARCHAR(255),
  DB_USER VARCHAR(255),
  DB_PASSWORD VARCHAR(255),
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE IF NOT EXISTS T_PLATFORM_PRIVATE
(
  ID INT NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_PLAN
(
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  START_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PLAN_ID VARCHAR(36) NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ORGANIZATION_ID, START_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS T_PLAN
(
  PLAN_ID VARCHAR(36) NOT NULL,
  PLAN_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (PLAN_ID)
);

CREATE TABLE IF NOT EXISTS T_PLAN_ITEM
(
  LIMIT_ID VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (LIMIT_ID)
);

CREATE TABLE IF NOT EXISTS T_PLAN_LIMIT
(
  PLAN_ID VARCHAR(36) NOT NULL,
  LIMIT_ID VARCHAR(255) NOT NULL,
  LIMIT_VALUE INT NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (PLAN_ID, LIMIT_ID)
);


/* plan values */
INSERT INTO T_PLAN_ITEM (LIMIT_ID, INFORMATIONS, CREATE_USER, LAST_UPDATE_USER) VALUES ('platform.workspaces', '{\"description\": \"default limit\", \"max\": 1000}', 'system', 'system');
INSERT INTO T_PLAN_ITEM (LIMIT_ID, INFORMATIONS, CREATE_USER, LAST_UPDATE_USER) VALUES ('platform.roles', '{\"description\": \"default limit\", \"max\": 1000}', 'system', 'system');
INSERT INTO T_PLAN_ITEM (LIMIT_ID, INFORMATIONS, CREATE_USER, LAST_UPDATE_USER) VALUES ('platform.users', '{\"description\": \"default limit\", \"max\": 10000}', 'system', 'system');
INSERT INTO T_PLAN (PLAN_ID, PLAN_NAME, INFORMATIONS, CREATE_USER, LAST_UPDATE_USER) VALUES ('_default', '_default plan', '{\"description\": \"default plan\"}', 'system', 'system');
INSERT INTO T_PLAN_LIMIT (PLAN_ID, LIMIT_ID, LIMIT_VALUE, CREATE_USER, LAST_UPDATE_USER) VALUES ('_default', 'platform.workspaces', 100, 'system', 'system');
INSERT INTO T_PLAN_LIMIT (PLAN_ID, LIMIT_ID, LIMIT_VALUE, CREATE_USER, LAST_UPDATE_USER) VALUES ('_default', 'platform.roles', 1000, 'system', 'system');
INSERT INTO T_PLAN_LIMIT (PLAN_ID, LIMIT_ID, LIMIT_VALUE, CREATE_USER, LAST_UPDATE_USER) VALUES ('_default', 'platform.users', 10000, 'system', 'system');
/* plan values */

CREATE TABLE T_REFRESH_TOKEN
(
    USER_ID VARCHAR(40) NOT NULL,
    SESSION_ID VARCHAR(40) NOT NULL,
    EXPIRE_TIMESTAMP DATETIME NULL,
    CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(40),
    LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_UPDATE_USER VARCHAR(40),
    PRIMARY KEY (USER_ID, SESSION_ID)
)
