CREATE USER app_user IDENTIFIED BY 'password';
CREATE DATABASE platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON platform.* TO app_user;

USE platform;

CREATE TABLE IF NOT EXISTS T_ORGANIZATION
(
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  ORGANIZATION_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_DB
(
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  DB_HOST VARCHAR(255),
  DB_PORT INT,
  DB_DATABASE VARCHAR(255),
  DB_USER VARCHAR(255),
  DB_PASSWORD VARCHAR(255),
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE IF NOT EXISTS T_PLATFORM_PRIVATE
(
  ID INT NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ID)
);
