-- 仮、本来はOrganization作成時にDBを作成
CREATE USER org1_user IDENTIFIED BY 'password';
CREATE DATABASE org1db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON org1db.* TO org1_user;

USE org1db;

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_PRIVATE
(
  ID INT NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS T_WORKSPACE
(
  WORKSPACE_ID VARCHAR(36) NOT NULL,
  WORKSPACE_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (WORKSPACE_ID)
);


-- 仮データ
-- INSERT INTO platform.T_ORGANIZATION (ORGANIZATION_ID, ORGANIZATION_NAME, INFORMATIONS) VALUES ("org1", "オーガナイゼーション１", "{}");
-- INSERT INTO platform.T_ORGANIZATION_DB (ORGANIZATION_ID, DB_HOST, DB_PORT, DB_DATABASE, DB_USER, DB_PASSWORD) VALUES ("org1", "platform-db", 3306, "org1db", "org1_user", "password");
-- INSERT INTO org1db.T_ORGANIZATION_PRIVATE (ID, INFORMATIONS) VALUES (1, JSON_OBJECT(
--  "USER_TOKEN_CLIENT_CLIENTID","org1",
--  "USER_TOKEN_CLIENT_ID","org1-ID",

--  "INTERNAL_API_CLIENT_CLIENTID","org1-woorkspaces",
--  "INTERNAL_API_CLIENT_ID","woorkspaces-ID",
--  "INTERNAL_API_CLIENT_SECRET","woorkspaces-client-secret",

--  "TOKEN_CHECK_CLIENT_CLIENTID","system-org1-auth",
--  "TOKEN_CHECK_CLIENT_ID","system-auth-ID",
--  "TOKEN_CHECK_CLIENT_SECRET","system-auth-client-secret"
-- ));
-- INSERT INTO org1db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("ws1", "ワークスペース１", "{}");
-- INSERT INTO org1db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("ws2", "ワークスペース２", "{}");
-- INSERT INTO org1db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("ws3", "ワークスペース３", "{}");
