-- 仮、本来はOrganization作成時にDBを作成
CREATE USER org1xxxxxxxx_user IDENTIFIED BY 'password';
CREATE DATABASE org1xxxxxxxx CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON org1xxxxxxxx.* TO org1xxxxxxxx_user;

USE org1xxxxxxxx;

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_PRIVATE
(
  ID INT NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS T_WORKSPACE
(
  WORKSPACE_ID VARCHAR(36) NOT NULL,
  WORKSPACE_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (WORKSPACE_ID)
);


-- 仮データ
-- INSERT INTO platform.T_ORGANIZATION (organization_id, organization_name, INFORMATIONS) VALUES ("exastro-common-auth", "ExastroCommonAuth", "{}");
-- INSERT INTO platform.T_ORGANIZATION_DB (organization_id, db_host, db_port, db_database, db_user, db_password) VALUES ("exastro-common-auth", "platform-db", 3306, "org1xxxxxxxx", "org1xxxxxxxx_user", "password");
-- INSERT INTO org1xxxxxxxx.T_ORGANIZATION_PRIVATE (ID, INFORMATIONS) VALUES (1, JSON_OBJECT(
--  "USER_TOKEN_CLIENT_CLIENTID","exastro-common-auth",
--  "USER_TOKEN_CLIENT_ID","exastro-common-auth-ID",

--  "INTERNAL_API_CLIENT_CLIENTID","exastro-common-auth-woorkspaces",
--  "INTERNAL_API_CLIENT_ID","woorkspaces-ID",
--  "INTERNAL_API_CLIENT_SECRET","woorkspaces-client-secret",

--  "TOKEN_CHECK_CLIENT_CLIENTID","system-exastro-common-auth-auth",
--  "TOKEN_CHECK_CLIENT_ID","system-auth-ID",
--  "TOKEN_CHECK_CLIENT_SECRET","system-auth-client-secret"
-- ));
-- INSERT INTO org1xxxxxxxx.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("workspace001", "workspace001", "{}");
-- INSERT INTO org1xxxxxxxx.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("workspace002", "workspace002", "{}");
-- INSERT INTO org1xxxxxxxx.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("workspaceAAA", "workspaceAAA", "{}");
-- INSERT INTO org1xxxxxxxx.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("workspaceBBB", "workspaceBBB", "{}");
