-- 仮、本来はOrganization作成時にDBを作成
CREATE USER org2_user IDENTIFIED BY 'password';
CREATE DATABASE org2db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON org2db.* TO org2_user;

USE org2db;

CREATE TABLE IF NOT EXISTS T_ORGANIZATION_PRIVATE
(
  ID INT NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS T_WORKSPACE
(
  WORKSPACE_ID VARCHAR(36) NOT NULL,
  WORKSPACE_NAME VARCHAR(255) NOT NULL,
  INFORMATIONS JSON NOT NULL,
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER VARCHAR(40),
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDATE_USER VARCHAR(40),
  PRIMARY KEY (WORKSPACE_ID)
);


-- 仮データ
-- INSERT INTO platform.T_ORGANIZATION (ORGANIZATION_ID, ORGANIZATION_NAME, INFORMATIONS) VALUES ("org2", "オーガナイゼーション２", "{}");
-- INSERT INTO platform.T_ORGANIZATION_DB (ORGANIZATION_ID, DB_HOST, DB_PORT, DB_DATABASE, DB_USER, DB_PASSWORD) VALUES ("org2", "platform-db", 3306, "org2db", "org2_user", "password");
-- INSERT INTO org2db.T_ORGANIZATION_PRIVATE (ID, INFORMATIONS) VALUES (1, JSON_OBJECT(
--  "USER_TOKEN_CLIENT_CLIENTID","org2",
--  "USER_TOKEN_CLIENT_ID","org2-ID",

--  "INTERNAL_API_CLIENT_CLIENTID","org2-woorkspaces",
--  "INTERNAL_API_CLIENT_ID","woorkspaces-ID",
--  "INTERNAL_API_CLIENT_SECRET","woorkspaces-client-secret",

--  "TOKEN_CHECK_CLIENT_CLIENTID","system-org2-auth",
--  "TOKEN_CHECK_CLIENT_ID","system-auth-ID",
--  "TOKEN_CHECK_CLIENT_SECRET","system-auth-client-secret"
-- ));
-- INSERT INTO org2db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("wsone", "workspace001", "{}");
-- INSERT INTO org2db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("wstwo", "workspace002", "{}");
-- INSERT INTO org2db.T_WORKSPACE (WORKSPACE_ID, WORKSPACE_NAME, INFORMATIONS) VALUES ("wsthree", "workspace003", "{}");
