# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}
@internal-api = http://platform-api:8000

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

# share ws_id (同じものを複数記載すると最後の設定値が渡される)
@ws_id = ws1

# 1 api to ###


### Get Agent User List
# @name agent_list
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/agent-users
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Create Agent User
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/agent-users
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
  "username": "agent-user-01",
  "agent_user_type": "ansible",
  "description": "ansible agent userです"
}

### Create Agent User Token
@agent_user_id = {{agent_list.response.body.$.data[0].id}}
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/agent-users/{{agent_user_id}}/refresh_tokens
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
}
