# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

@ws_id = ws1

# 1 api to ###

###

GET {{base_sys_url}}/api/platform/organizations
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

### OrganizationService POST

POST {{base_sys_url}}/api/platform/organizations?retry=1
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}
content-type: application/json

{
  "id": "org1",
  "name": "organization of org1",
  "organization_managers": [
    {
      "username": "admin",
      "email": "org1@example.com",
      "firstName": "org1",
      "lastName": "administrator",
      "credentials": [
        {
          "type": "password",
          "value": "password",
          "temporary": false
        }
      ],
      "requiredActions": [
        "UPDATE_PROFILE"
      ],
      "enabled": true
    }
  ],
  "plan": {},
  "optionsIta": {
    "drivers": {
      "ci_cd": true,
      "oase": false,
      "terraform_cli": true,
      "terraform_cloud_ep": true
    }
  }
}

### OrganizationService PUT
PUT {{base_sys_url}}/api/platform/organizations/{{org_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
  "name": "name of org",
  "enabled": true,
  "optionsIta": {
    "drivers": {
      "terraform_cloud_ep": true,
      "terraform_cli": true,
      "ci_cd": true,
      "oase": true
    }
  }
}

### OrganizationService DELETE

DELETE {{base_sys_url}}/api/platform/organizations/{{org_id}}
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

###

GET {{base_sys_url}}/api/platform/organizations/{{org_id}}
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

###

PUT {{base_sys_url}}/api/platform/organizations/{{org_id}}
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}
content-type: application/json

{
  "name": "organization of org1",
  "enabled": true
}

###

GET {{base_sys_url}}/api/platform/plans
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

###

GET {{base_sys_url}}/api/platform/plan_items
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

###

GET {{base_sys_url}}/api/platform/{{org_id}}/plans
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}

###

POST {{base_sys_url}}/api/platform/plans
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}
content-type: application/json

{
  "id": "plan-1",
  "name": "name of plan",
  "informations": {
    "description": "string"
  },
  "limits": {
    "ita.organization.ansible.execution_limit": 25,
    "platform.workspaces": 500,
    "platform.roles": 500,
    "platform.users": 1000
  }
}

###

GET {{base_sys_url}}/api/platform/settings/common
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}


###

# @name sys_login

POST {{base_sys_url}}/auth/realms/master/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

client_id=admin-cli
&username={{sys-user-id}}
&password={{sys-user-pw}}
&grant_type=password

###

# please sendRquest sys_login execution
@authToken = {{sys_login.response.body.access_token}}

GET http://keycloak:8080/auth/admin/realms/master
Authorization: Bearer {{authToken}}

###

# please sendRquest sys_login execution
@authToken = {{sys_login.response.body.access_token}}

PUT http://keycloak:8080/auth/admin/realms/master
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "sslRequired": "none"
}


###

# audit log download get
GET {{base_org_url}}/api/{{org_id}}/platform/auditlog/download
Authorization: Basic {{org-user-id}} {{org-user-pw}}

###

# audit log download post
# @name auditlog_download
POST {{base_org_url}}/api/{{org_id}}/platform/auditlog/download
Authorization: Basic {{sys-user-id}} {{sys-user-pw}}
content-type: application/json

{
  "ts_from": "2024-06-01 00:00:00",
  "ts_to": "2024-06-30 23:59:59"
}

###

# First, audit log download post
@download_id =  {{auditlog_download.response.body.data.download_id}}

# audit log download get by query
GET {{base_org_url}}/api/{{org_id}}/platform/auditlog/download
    ?download_id={{download_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Get Notification
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users
Authorization: Basic {{org-user-id}} {{org-user-pw}}

###
