# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}
@internal-api = http://platform-api:8000
@job_id = XXXXXXXXXXXXXXXXXXXXXXXXXX
@import_file = /workspace/test/test.xlsx

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

# 1 api to ###

###

# @name org_login

POST {{base_org_url}}/auth/realms/{{org_id}}/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

client_id=admin-cli
&username={{org-user-id}}
&password={{org-user-pw}}
&grant_type=password

###

### Download template file for bulk import/delete user
# please sendRquest org_login execution
@authToken = Bearer {{org_login.response.body.access_token}}

POST {{base_org_url}}/api/{{org_id}}/platform/jobs/users/bulk/format
Content-Type: application/x-www-form-urlencoded

authorization={{authToken}}


### Jobs user import
POST {{base_org_url}}/api/{{org_id}}/platform/jobs/users/bulk/import
Authorization: Basic {{org-user-id}} {{org-user-pw}}
Content-Type: multipart/form-data; boundary=hogehoge

--hogehoge
Content-Disposition: form-data; name="import_file"; filename="sample_delete.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< {{import_file}}
--hogehoge--

### Jobs user delete
POST {{base_org_url}}/api/{{org_id}}/platform/jobs/users/bulk/delete
Authorization: Basic {{org-user-id}} {{org-user-pw}}
Content-Type: multipart/form-data; boundary=hogehoge

--hogehoge
Content-Disposition: form-data; name="import_file"; filename="sample_delete.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< {{import_file}}
--hogehoge--


### Jobs user import status
GET {{base_org_url}}/api/{{org_id}}/platform/jobs/users/bulk/status
Authorization: Basic {{org-user-id}} {{org-user-pw}}


### Jobs user import status job_id
GET {{base_org_url}}/api/{{org_id}}/platform/jobs/users/bulk/status/{{job_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}


### Jobs user export
# @name jobs_users_export
POST {{base_org_url}}/api/{{org_id}}/platform/jobs/users/export
Authorization: Basic {{org-user-id}} {{org-user-pw}}
Content-Type: application/json

### Jobs user export status job id

# First, Post Jobs user export
@export_job_id =  {{jobs_users_export.response.body.data.job_id}}

GET {{base_org_url}}/api/{{org_id}}/platform/jobs/users/export/status/{{export_job_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}
Content-Type: application/json

### Jobs user export status
GET {{base_org_url}}/api/{{org_id}}/platform/jobs/users/export/status
Authorization: Basic {{org-user-id}} {{org-user-pw}}
Content-Type: application/json


