# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}
@internal-api = http://platform-api:8000

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

# share ws_id (同じものを複数記載すると最後の設定値が渡される)
@ws_id = ws1

# 1 api to ###


### Create Mailserver
POST {{base_org_url}}/api/{{org_id}}/platform/settings/mailserver
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
    "SMTP_HOST": "smpt-host.example.com",
    "SMTP_PORT": "25",
    "SEND_FROM": "send-from@example.com",
    "SEND_NAME": "send name",
    "REPLY_TO": "replay-to@example.com",
    "REPLY_NAME": "replay name",
    "ENVELOPE_FROM": "envelope-from@example.com",
    "SSL_ENABLE": false,
    "START_TLS_ENABLE": true,
    "AUTHENTICATION_ENABLE": true,
    "AUTHENTICATION_USER": "user",
    "AUTHENTICATION_PASSWORD": "password"
}