# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

# share ws_id (同じものを複数記載すると最後の設定値が渡される)
@ws_id = ws1

# 1 api to ###


### Get Notification
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Create Notifications(kind=mail)
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

[
  {
    "id": "destination-mail-01",
    "name": "name of mail destination",
    "kind": "Mail",
    "destination_informations": [{
        "address_header": "to",
        "email": "example@example.com"
    }],
    "conditions": {
      "ita": {
        "event_type": {
            "new": true, "evaluated": false, "timeout": true, "undetected": false
        }
      }
    }
  }
]


### Create Notifications(kind=teams)
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

[
  {
    "id": "destination-teams-01",
    "name": "name of teams destination",
    "kind": "Teams",
    "destination_informations": [{
      "webhook": "https://example.com/teams"
    }],
    "conditions": {
      "ita": {
        "event_type": {
          "new": true, "evaluated": true, "timeout": true, "undetected": true
        }
      }
    }
  }
]


### Register for message notifications
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/notifications
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

[
  {
    "destination_id": "destination-teams-01",
    "func_id": "00000000",
    "func_informations": {
      "key-1": "value-1",
      "key-2": "value-2"
    },
    "message": {
      "title": "subjects",
      "message": "event message"
    }
  }
]


### Get Notification Desiti

@dest_id = destination-mail-01
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications/{{dest_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}


### Get Notification Desitination list

GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications?event_type_true=ita.event_type.new|ita.event_type.evaluated&event_type_false=ita.event_type.timeout|ita.event_type.undetected
Authorization: Basic {{org-user-id}} {{org-user-pw}}


### Get Notification Desitination list

GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications?event_type_false=ita.event_type.new
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Get Notification Desitination list

GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/settings/notifications
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Get Notification list

GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/notifications?match=string'""22/|ass&like_before="111//##""
Authorization: Basic {{org-user-id}} {{org-user-pw}}
accept: application/json

### Get Notification list

GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/notifications?mutch={"key":"aaa", "value":"cccc"}
Authorization: Basic {{org-user-id}} {{org-user-pw}}
accept: application/json


### Get Notification list
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/notifications?page_size=100&current_page=1&details_info=false&match=ita.event_type.new|true|ita.event_type.timeout|true&like_before=ita.event_type.new|ue|ita.event_type.timeout|true&like_all=ita.event_type.timeout|t
Authorization: Basic {{org-user-id}} {{org-user-pw}}
