# not quate strings
@sys-user-id = admin
@sys-user-pw = password
@org-user-id = admin
@org-user-pw = password
@base_sys_url = http://platform-auth:{{sys-mng-port}}
@base_org_url = http://platform-auth:{{org-mng-port}}
@internal-api = http://platform-api:8000

# share org_id (同じものを複数記載すると最後の設定値が渡される)
@org_id = org1

# share ws_id (同じものを複数記載すると最後の設定値が渡される)
@ws_id = ws1

# share user_id (同じものを複数記載すると最後の設定値が渡される)
@service_account_user_id = {{service_account_users_list_api.response.body.$.data[0].id}}

# token
@service_account_user_refresh_token = {{service_account_user_refresh_token_api.response.body.$.data.refresh_token}}
@service_account_user_access_token = {{service_account_user_access_token_api.response.body.$.access_token}}

# 1 api to ###


### Get Service Account User List
# @name service_account_users_list_api
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Create Service Account User
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
  "username": "service-account-user-01",
  "service_account_user_type": "ansible-execution-agent",
  "description": "service account userです"
}

### Get Service Account User
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Update Service Account User
PUT {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
  "description": "service account userです※更新後"
}

### Delete Service Account User
DELETE {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Create Agent User Token
# @name service_account_user_refresh_token_api
POST {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}/refresh_tokens
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

{
}

### Get Service Account User Token List
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}/refresh_tokens
Authorization: Basic {{org-user-id}} {{org-user-pw}}
content-type: application/json

### Delete Service Account User Token
DELETE {{base_org_url}}/api/{{org_id}}/platform/workspaces/{{ws_id}}/service-account-users/{{service_account_user_id}}/refresh_tokens
Authorization: Basic {{org-user-id}} {{org-user-pw}}

### Get Access Token - 発行したrefresh tokenでAPIをコールする
# @name service_account_user_access_token_api
POST {{base_org_url}}/auth/realms/{{org_id}}/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

client_id=_{{org_id}}-api
&grant_type=refresh_token
&refresh_token={{service_account_user_refresh_token}}


### Get Workspaces - 発行したaccess tokenでAPIをコールする
GET {{base_org_url}}/api/{{org_id}}/platform/workspaces
Authorization: Bearer {{service_account_user_access_token}}
