# Default values for platform-setup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  authGlobalDefinition:
    name: auth-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-platform
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      TZ: "Asia/Tokyo"
      PYTHONIOENCODING: utf-8
      PLATFORM_API_PROTOCOL: "http"
      PLATFORM_API_HOST: "platform-api"
      PLATFORM_API_PORT: "8000"
      PLATFORM_WEB_PROTOCOL: "http"
      PLATFORM_WEB_HOST: "platform-web"
      PLATFORM_WEB_PORT: "8000"
    secret:
      ENCRYPT_KEY: ""
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels:
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  keycloakDefinition:
    name: keycloak
    enabled: true
    config:
      API_KEYCLOAK_PROTOCOL: "http"
      API_KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      API_KEYCLOAK_PORT: "8080"
      KEYCLOAK_PROTOCOL: "http"
      KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      KEYCLOAK_PORT: "8080"
      KEYCLOAK_MASTER_REALM: "master"
      KEYCLOAK_DB_DATABASE: "keycloak"
    secret:
      KEYCLOAK_USER: ""
      KEYCLOAK_PASSWORD: ""
      KEYCLOAK_DB_USER: ""
      KEYCLOAK_DB_PASSWORD: ""
  itaDefinition:
    name: ita
    enabled: true
    config:
      ITA_WEB_PROTOCOL: "http"
      ITA_WEB_HOST: "ita-web-server.exastro-it-automation.svc"
      ITA_WEB_PORT: "8000"
      ITA_API_PROTOCOL: "http"
      ITA_API_HOST: "ita-api-organization.exastro-it-automation.svc"
      ITA_API_PORT: "8080"
      ITA_API_ADMIN_PROTOCOL: "http"
      ITA_API_ADMIN_HOST: "ita-api-admin.exastro-it-automation.svc"
      ITA_API_ADMIN_PORT: "8080"
  authDatabaseDefinition:
    name: auth-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb.exastro-platform.svc"
      DB_PORT: "3306"
      DB_DATABASE: "platform"
    secret:
      DB_ADMIN_USER: ""
      DB_ADMIN_PASSWORD: ""
      DB_USER: ""
      DB_PASSWORD: ""

extraEnv:
  LOG_LEVEL: "INFO"
  TIMEOUT: "10"

completionCount: 1

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

volumeMounts:
  mountPath:
    createDB:
      path: /createdb.sql
      subPath: createdb.sql
    conf:
      path: /etc/mysql/conf.d

database:
  initContainerImage:
    repository: mariadb
    tag: "10.9"
    pullPolicy: IfNotPresent

  image:
    repository: mariadb
    tag: "10.9"
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  livenessCheck: |-
    #!/bin/bash
    i=1
    echo "HOST: ${DB_HOST}"
    until mysqladmin ping --host=${DB_HOST} --user=${DB_ADMIN_USER} --password=${DB_ADMIN_PASSWORD} --silent; do
      echo `date`": Can not connect to Database."
      sleep $i
      i=$(( i * 2 ))
    done
    echo `date`": Completely connect to Database."
    exit 0

  initializeDatabase: |-
    mysql --host=${DB_HOST} --user=${DB_ADMIN_USER} --password=${DB_ADMIN_PASSWORD} < /createdb.sql

  databaseConfig:
    name: mysqld-conf
    customCnf: |-
      [mysqld]
      character-set-server=utf8mb4
      collation-server=utf8mb4_bin
      secure_file_priv=/tmp
      [client]
      default-character-set=utf8mb4

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

keycloak:
  extraEnv:
    LOG_LEVEL: "INFO"
    TIMEOUT: "10"

  initContainerImage:
    repository: busybox
    tag: ""
    pullPolicy: IfNotPresent

  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  livenessCheck: |-
    #!/bin/bash
    i=1
    echo "HOST: ${API_KEYCLOAK_PROTOCOL}://${API_KEYCLOAK_HOST}:${API_KEYCLOAK_PORT}"
    until wget --spider -T ${TIMEOUT} ${API_KEYCLOAK_PROTOCOL}://${API_KEYCLOAK_HOST}:${API_KEYCLOAK_PORT}/auth/health; do
      echo `date`": Can not connect to KeyCloak."
      sleep $i
      i=$(( i * 2 ))
    done
    echo `date`": Completely connect to KeyCloak."
    exit 0

  initializeKeycloak: |-
    python3 /app/platform_init.py

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
