#   Copyright 2023 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

value:
  {
    "result": 200,
    "message": "SUCCESS",
    "ts": "2023-11-02T05:36:41.258Z",
    "data":{
      "id": "00000001Z7ZXFAED6872F6C9W8",
      "name": "destinations of teams settings",
      "kind": "Teams",
      "conditions": {
        "ita":{
          "event_type": {
            "new": true, "evaluated": true, "timeout": false, "undetected": false
          }
        }
      },
      "destination_informations": [
        { "webhook": "https://xxxxxxxx.webhook.office.com/webhookb/xxxxxxxx-xxxxxx-xxxx-xxxx-xxxxxxxxxxxx" }
      ],
      "create_timestamp": "2023-11-02T05:36:41.258Z",
      "create_user": "string",
      "last_update_timestamp": "2023-11-02T05:36:41.258Z",
      "last_update_user": "string"
    }
  }